### ISSUE TITLE
Object.assign() undefined

### ISSUE THREAD

**Issue by nicholaswyoung** [vdemedes/mailman#2]
In the most recent release of Node/io.js, Object.assign is undefined (see [line #178](https://github.com/vdemedes/mailman/blob/master/build/mailman.js#L178).)

This is probably an easy fix, just by including a [new transform in the Babel/6to5 config](https://github.com/babel/babel/issues/377). I can assemble a pull request if you'd like.

**Comment by vdemedes** [comment]
Couldn't reproduce, just ran tests and they all pass.

**Comment by nicholaswyoung** [comment]
Weird. I've had this issue repeatedly on io.js with Mailman. In the end, I just used something else. If I encounter it again in relation to this module, I'll re-open.
